@echo off
echo Cleaning Flutter build...
call flutter clean
echo Removing Gradle cache...
rmdir /s /q "%USERPROFILE%\.gradle\caches"
echo Cleaning Android build...
rmdir /s /q "android\.gradle"
rmdir /s /q "android\app\build"
rmdir /s /q "build"
echo Reinstalling dependencies...
call flutter pub get
echo Build environment clean-up complete!
echo Run "flutter build appbundle" or "flutter build apk --split-per-abi" to generate a new build
