name: eatfast_mobile
description: "Eat Fast - Fast and reliable food delivery app for Cameroon. Order from your favorite restaurants with real-time tracking, secure payments, and exceptional customer service."
publish_to: 'none'

version: 1.0.0+1

# App Store Metadata
# Update these values before submitting to app stores
app_store_metadata:
  android:
    package_name: "com.eatfast.mobile"
    min_sdk_version: 21
    target_sdk_version: 34
  ios:
    bundle_id: "com.eatfast.mobile"
    minimum_os_version: "12.0"
  web:
    base_href: "/"

# Android specific configuration
android:
  namespace: "com.eatfast.mobile"

# iOS specific configuration
ios:
  bundle_id: "com.eatfast.mobile"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  
  # Navigation
  go_router: ^14.2.3
  
  # Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  
  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  
  # UI & Animations
  lottie: ^3.1.2
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.1
  
  # Maps & Location
  google_maps_flutter: ^2.6.0
  location: ^6.0.2
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  
  # Authentication & Social
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  local_auth: ^2.2.0
  
  # Media & Files
  image_picker: ^1.0.7
  # image_cropper: ^8.0.2  # Temporarily disabled due to compatibility issues
  file_picker: ^8.0.0+1
  image: ^4.1.7  # For image optimization service
  path_provider: ^2.1.3  # For cache manager and image service
  
  # Local Notifications (backend sends email notifications)
  flutter_local_notifications: ^17.1.2

  # Push Notifications (using backend web push instead of Firebase)
  # firebase_messaging: ^15.1.3  # REMOVED: Using backend web push

  # Monitoring & Error Tracking (Firebase is best for Flutter mobile apps)
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_performance: ^0.10.0+8
  firebase_analytics: ^11.3.3

  # Real-time Communication
  socket_io_client: ^2.0.3+1
  
  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.6
  permission_handler: ^11.3.1
  share_plus: ^12.0.0
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  crypto: ^3.0.3
  logging: ^1.2.0
  screenshot: ^3.0.0
  
  # Payment
  flutter_stripe: ^10.1.1

  # AI & Speech
  speech_to_text: ^7.3.0

  # Charts & Analytics
  fl_chart: ^0.68.0

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.1

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1
  freezed: ^2.5.2
  
  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.3
  collection: ^1.18.0
  integration_test:
    sdk: flutter
  
  # App Optimization
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true  # Enable internationalization

  assets:
    - assets/images/
    - assets/logo/
    - assets/animations/
    - assets/icons/
    - assets/avatar/
    - assets/i18n/

  # fonts:
    # - family: Poppins
    #   fonts:
    #     - asset: fonts/Poppins-Regular.ttf
    #     - asset: fonts/Poppins-Medium.ttf
    #       weight: 500
    #     - asset: fonts/Poppins-SemiBold.ttf
    #       weight: 600
    #     - asset: fonts/Poppins-Bold.ttf
    #       weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
# For details regarding fonts from package dependencies,
# see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/eat-fast-logo.png
  color_dark: "#1a1a1a"
  image_dark: assets/logo/eat-fast-logo.png

  android_12:
    image: assets/logo/eat-fast-logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/logo/eat-fast-logo.png
    icon_background_color_dark: "#1a1a1a"

  web: false